### ISSUE TITLE
Choosing a project name

### ISSUE THREAD

**Issue by unintendedbear** [proyectopetra/OpenDataHackathon#11]
Please leave here your proposals.

CletusAnalyser ?

**Comment by afercab** [comment]
NodeTracker.

**Comment by unintendedbear** [comment]
Chosen name: PETRA

**Comment by JJ** [comment]
Edit the GlobalUrbanDataFest and add @github

Please try also and use IBM BlueMix, there are prizes involved.

2015-02-21 11:58 GMT+01:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> Chosen name: PETRA
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/global-urban-datafest/OpenDataHackathon/issues/11#issuecomment-75366750
> .

## 

JJ
