### ISSUE TITLE
Convert XLS multi-sheet files to one CSV

### ISSUE THREAD

**Issue by fergunet** [proyectopetra/OpenDataHackathon#14]

**Comment by fergunet** [comment]
I managed to do this with this macro: http://www.jpstacey.info/blog/2014-09-12/exporting-all-libreoffice-worksheets-csv

I will close this issue when I upload all the CSVs of issue #1

**Comment by JJ** [comment]
You're doing a great job, guys

2015-02-21 18:14 GMT+01:00 Pablo García Sánchez notifications@github.com:

> I managed to do this with this macro:
> http://www.jpstacey.info/blog/2014-09-12/exporting-all-libreoffice-worksheets-csv
> 
> I will close this issue when I upload all the CSVs of issue #1
> https://github.com/global-urban-datafest/grx-PETRA/issues/1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/global-urban-datafest/grx-PETRA/issues/14#issuecomment-75381354
> .

## 

JJ
