### ISSUE TITLE
Could you add city prefix to repo name?

### ISSUE THREAD

**Issue by songgao** [proyectopetra/OpenDataHackathon#15]
Hey! Congrats on creating the repo!

Could you please add prefix to the repo name? Since we've got teams from all over the world under this organization, adding city prefix will make it easier to tell which project is from which city. GitHub will automatically track the renaming so as long as nobody else create a repo with your old repo name, nothing should be broken :D

**Comment by fergunet** [comment]
Done! Added the "grx-" prefix :)

**Comment by songgao** [comment]
Thanks!
