### ISSUE TITLE
Transferir este repo a GlobalUrbanDatafest

### ISSUE THREAD

**Issue by JJ** [proyectopetra/OpenDataHackathon#7]
¿Me dais permiso para transferir el proyecto a GlobalUrbanDatafest? https://github.com/global-urban-datafest
Cuando acabe el hackatón del fin de semana se puede volver a su sitio.

**Comment by fergunet** [comment]
Ok. Cuéntanos también qué otras cosas tenemos que hacer.

El sábado, 21 de febrero de 2015, Juan Julián Merelo Guervós <
notifications@github.com> escribió:

> ¿Me dais permiso para transferir el proyecto a GlobalUrbanDatafest?
> https://github.com/global-urban-datafest
> Cuando acabe el hackatón del fin de semana se puede volver a su sitio.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/proyectopetra/OpenDataHackathon/issues/7.

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by JJ** [comment]
Os he mandado un email con el resto de las cosas para acceder a los premios
y eso...

El 21 de febrero de 2015, 10:26, Pablo García Sánchez <
notifications@github.com> escribió:

> Ok. Cuéntanos también qué otras cosas tenemos que hacer.
> 
> El sábado, 21 de febrero de 2015, Juan Julián Merelo Guervós <
> notifications@github.com> escribió:
> 
> > ¿Me dais permiso para transferir el proyecto a GlobalUrbanDatafest?
> > https://github.com/global-urban-datafest
> > Cuando acabe el hackatón del fin de semana se puede volver a su sitio.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/proyectopetra/OpenDataHackathon/issues/7.
> 
> ## 
> 
> Dr. Pablo García Sánchez
> University of Granada
> http://www.ugr.es/~pablogarcia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/proyectopetra/OpenDataHackathon/issues/7#issuecomment-75363668
> .

## 

JJ
